# Generated by Django 5.2.5 on 2025-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
